name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
authors:     [NVX (Neo_Vortex), CyberTiger, RoyCurtis]
website:     https://github.com/Gamealition/GCleanroomGenerator
main:        io.nv.bukkit.CleanroomGenerator.CleanroomGenerator
load:        startup
